modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/Waystones/issues"

[[mods]]
modId="waystones"
version="${file.jarVersion}"
displayName="Waystones"
displayURL="https://blay09.net/mods/waystones"
logoFile="waystones-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Teleport back to activated waystones. For Survival, Adventure or Servers.
'''

[[dependencies.waystones]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waystones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waystones]]
    modId="balm"
    mandatory=true
    versionRange="[3.1.0,)"
    ordering="NONE"
    side="BOTH"